[package]
name = "apollo-router"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
common-utils = { path = "../common-utils" }
apollo-router = { git = "https://github.com/apollographql/router", tag = "v0.10.0" }
anyhow = "1.0.58"
async-trait = "0.1.56"
futures = "0.3.21"
schemars = "0.8.10"
jsonwebtoken = "8.1.1"
serde = "1.0.138"
serde_json = "1.0.82"
tokio = { version = "1.19.2", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1.34"
http = "0.2.8"
dotenv = "0.15.0"
