[package]
name = "planets-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2018"

[dependencies]
common-utils = { path = "../common-utils" }
async-graphql = { version = "2.8.5", features = ["dataloader"] }
async-graphql-actix-web = "2.8.5"
actix-web = "3.3.2"
actix-rt = "1.1.1"
actix-web-actors = "3.0.0"
futures = "0.3.15"
async-trait = "0.1.50"
bigdecimal = { version = "0.1.2", features = ["serde"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
diesel = { version = "1.4.6", features = ["postgres", "r2d2", "numeric"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
strum = "0.20.0"
strum_macros = "0.20.1"
rdkafka = { version = "0.26.0", features = ["cmake-build"] }
async-stream = "0.3.1"
lazy_static = "1.4.0"

[dev-dependencies]
jsonpath_lib = "0.2.6"
testcontainers = "0.12.0"
