[package]
name = "planets-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
common-utils = { path = "../common-utils" }
async-graphql = { version = "4.0.4", features = ["dataloader"] }
async-graphql-actix-web = "4.0.4"
actix-web = "4.1.0"
actix-rt = "2.7.0"
actix-web-actors = "4.1.0"
futures = "0.3.21"
async-trait = "0.1.56"
bigdecimal = { version = "0.1.2", features = ["serde"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "numeric"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
strum = "0.24.1"
strum_macros = "0.24.2"
rdkafka = { version = "0.28.0", features = ["cmake-build"] }
async-stream = "0.3.3"
lazy_static = "1.4.0"

[dev-dependencies]
jsonpath_lib = "0.3.0"
testcontainers = "0.14.0"
