[package]
name = "satellites-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
async-graphql = { version = "4.0.13", features = ["chrono"] }
async-graphql-actix-web = "4.0.13"
actix-web = "4.2.0"
actix-rt = "2.7.0"
serde = { version = "1.0.144", features = ["derive"] }
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "2.0.0"
chrono = { version = "0.4.22", features = ["serde"] }
dotenv = "0.15.0"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
serde_json = "1.0.85"
jsonpath_lib = "0.3.0"
testcontainers = "0.14.0"
