[package]
name = "satellites-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
async-graphql = { version = "3.0.6", features = ["chrono"] }
async-graphql-actix-web = "3.0.6"
actix-web = "4.0.0-beta.11"
actix-rt = "2.4.0"
serde = { version = "1.0.130", features = ["derive"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
strum = "0.23.0"
strum_macros = "0.23.0"

[dev-dependencies]
serde_json = "1.0.71"
jsonpath_lib = "0.3.0"
testcontainers = "0.12.0"
