[package]
name = "satellites-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
async-graphql = { version = "4.0.6", features = ["chrono"] }
async-graphql-actix-web = "4.0.6"
actix-web = "4.1.0"
actix-rt = "2.7.0"
serde = { version = "1.0.142", features = ["derive"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.20", features = ["serde"] }
dotenv = "0.15.0"
strum = "0.24.1"
strum_macros = "0.24.2"

[dev-dependencies]
serde_json = "1.0.83"
jsonpath_lib = "0.3.0"
testcontainers = "0.14.0"
