[package]
name = "common-utils"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.3.1"
serde = { version = "1.0.166", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.1"
