[package]
name = "common-utils"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.1.0"
serde = { version = "1.0.142", features = ["derive"] }
strum = "0.24.1"
strum_macros = "0.24.2"
